package week03_2.gui;

import week03_2.ArrayList;
import week03_2.LinkedList;
import week03_2.OrdArrayList;
import week03_2.OrdLinkedList;

import java.util.Objects;

public class CS305GUI extends javax.swing.JFrame {

    /**
     * Creates new form CS305GUI
     */
    public CS305GUI() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        arrayPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teRead = new javax.swing.JTextArea();
        eventBox = new javax.swing.JComboBox<>();
        applyBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teWrite = new javax.swing.JTextArea();
        givenItem = new javax.swing.JTextField();
        ordArrayPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        teRead1 = new javax.swing.JTextArea();
        eventBox1 = new javax.swing.JComboBox<>();
        applyBtn1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        labelTime1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        teWrite1 = new javax.swing.JTextArea();
        givenItem1 = new javax.swing.JTextField();
        linkedPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        teRead2 = new javax.swing.JTextArea();
        eventBox2 = new javax.swing.JComboBox<>();
        applyBtn2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        labelTime2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        teWrite2 = new javax.swing.JTextArea();
        givenItem2 = new javax.swing.JTextField();
        ordLinkedPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        teRead3 = new javax.swing.JTextArea();
        eventBox3 = new javax.swing.JComboBox<>();
        applyBtn3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        labelTime3 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        teWrite3 = new javax.swing.JTextArea();
        givenItem3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoodyUI");
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Enter the array seperated by space: ");

        teRead.setColumns(20);
        teRead.setRows(5);
        jScrollPane1.setViewportView(teRead);

        eventBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"build", "delete", "insert", "selectionSort", "find", "display"}));
        eventBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBoxActionPerformed(evt);
            }
        });

        applyBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        applyBtn.setText("Apply");
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Choose the method:");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 2, 14)); // NOI18N
        jLabel3.setText("Result");

        jLabel4.setText("Time in millis:");

        labelTime.setForeground(new java.awt.Color(204, 0, 0));
        labelTime.setText(" ");

        teWrite.setEditable(false);
        teWrite.setColumns(20);
        teWrite.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        teWrite.setRows(5);
        jScrollPane2.setViewportView(teWrite);

        givenItem.setEnabled(false);

        javax.swing.GroupLayout arrayPanelLayout = new javax.swing.GroupLayout(arrayPanel);
        arrayPanel.setLayout(arrayPanelLayout);
        arrayPanelLayout.setHorizontalGroup(
                arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(arrayPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1)
                                        .addComponent(jSeparator2)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arrayPanelLayout.createSequentialGroup()
                                                .addGroup(arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(arrayPanelLayout.createSequentialGroup()
                                                                .addGroup(arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(arrayPanelLayout.createSequentialGroup()
                                                                .addComponent(givenItem)
                                                                .addGap(72, 72, 72)))
                                                .addGroup(arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(applyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(eventBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                                        .addGroup(arrayPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arrayPanelLayout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addGap(375, 375, 375))
        );
        arrayPanelLayout.setVerticalGroup(
                arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(arrayPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eventBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(applyBtn)
                                        .addComponent(givenItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(arrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(labelTime))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Array List", arrayPanel);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Enter the array seperated by space: ");

        teRead1.setColumns(20);
        teRead1.setRows(5);
        jScrollPane3.setViewportView(teRead1);

        eventBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"build", "delete", "insert", "find", "display"}));
        eventBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBox1ActionPerformed(evt);
            }
        });

        applyBtn1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        applyBtn1.setText("Apply");
        applyBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtn1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Choose the method:");

        jLabel7.setFont(new java.awt.Font("Sitka Text", 2, 14)); // NOI18N
        jLabel7.setText("Result");

        jLabel8.setText("Time in millis:");

        labelTime1.setForeground(new java.awt.Color(204, 0, 0));
        labelTime1.setText(" ");

        teWrite1.setEditable(false);
        teWrite1.setColumns(20);
        teWrite1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        teWrite1.setRows(5);
        jScrollPane4.setViewportView(teWrite1);

        givenItem1.setEnabled(false);

        javax.swing.GroupLayout ordArrayPanelLayout = new javax.swing.GroupLayout(ordArrayPanel);
        ordArrayPanel.setLayout(ordArrayPanelLayout);
        ordArrayPanelLayout.setHorizontalGroup(
                ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ordArrayPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator3)
                                        .addComponent(jSeparator4)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordArrayPanelLayout.createSequentialGroup()
                                                .addGroup(ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(ordArrayPanelLayout.createSequentialGroup()
                                                                .addGroup(ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(ordArrayPanelLayout.createSequentialGroup()
                                                                .addComponent(givenItem1)
                                                                .addGap(72, 72, 72)))
                                                .addGroup(ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(applyBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(eventBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                                        .addGroup(ordArrayPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane4))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordArrayPanelLayout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(375, 375, 375))
        );
        ordArrayPanelLayout.setVerticalGroup(
                ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ordArrayPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eventBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(applyBtn1)
                                        .addComponent(givenItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ordArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(labelTime1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Order Array List", ordArrayPanel);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Enter the array seperated by space: ");

        teRead2.setColumns(20);
        teRead2.setRows(5);
        jScrollPane5.setViewportView(teRead2);

        eventBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"build", "delete", "insert", "selectionSort", "find", "display"}));
        eventBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBox2ActionPerformed(evt);
            }
        });

        applyBtn2.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        applyBtn2.setText("Apply");
        applyBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtn2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Choose the method:");

        jLabel11.setFont(new java.awt.Font("Sitka Text", 2, 14)); // NOI18N
        jLabel11.setText("Result");

        jLabel12.setText("Time in millis:");

        labelTime2.setForeground(new java.awt.Color(204, 0, 0));
        labelTime2.setText(" ");

        teWrite2.setEditable(false);
        teWrite2.setColumns(20);
        teWrite2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        teWrite2.setRows(5);
        jScrollPane6.setViewportView(teWrite2);

        givenItem2.setEnabled(false);

        javax.swing.GroupLayout linkedPanelLayout = new javax.swing.GroupLayout(linkedPanel);
        linkedPanel.setLayout(linkedPanelLayout);
        linkedPanelLayout.setHorizontalGroup(
                linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(linkedPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator5)
                                        .addComponent(jSeparator6)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linkedPanelLayout.createSequentialGroup()
                                                .addGroup(linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(linkedPanelLayout.createSequentialGroup()
                                                                .addGroup(linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(linkedPanelLayout.createSequentialGroup()
                                                                .addComponent(givenItem2)
                                                                .addGap(72, 72, 72)))
                                                .addGroup(linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(applyBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(eventBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                                        .addGroup(linkedPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane6))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linkedPanelLayout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(375, 375, 375))
        );
        linkedPanelLayout.setVerticalGroup(
                linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(linkedPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eventBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addGap(27, 27, 27)
                                .addGroup(linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(applyBtn2)
                                        .addComponent(givenItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(linkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(labelTime2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Linked List", linkedPanel);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Enter the array seperated by space: ");

        teRead3.setColumns(20);
        teRead3.setRows(5);
        jScrollPane7.setViewportView(teRead3);

        eventBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"build", "delete", "insert", "find", "display"}));
        eventBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBox3ActionPerformed(evt);
            }
        });

        applyBtn3.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        applyBtn3.setText("Apply");
        applyBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtn3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Choose the method:");

        jLabel15.setFont(new java.awt.Font("Sitka Text", 2, 14)); // NOI18N
        jLabel15.setText("Result");

        jLabel16.setText("Time in millis:");

        labelTime3.setForeground(new java.awt.Color(204, 0, 0));
        labelTime3.setText(" ");

        teWrite3.setEditable(false);
        teWrite3.setColumns(20);
        teWrite3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        teWrite3.setRows(5);
        jScrollPane8.setViewportView(teWrite3);

        givenItem3.setEnabled(false);

        javax.swing.GroupLayout ordLinkedPanelLayout = new javax.swing.GroupLayout(ordLinkedPanel);
        ordLinkedPanel.setLayout(ordLinkedPanelLayout);
        ordLinkedPanelLayout.setHorizontalGroup(
                ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ordLinkedPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator7)
                                        .addComponent(jSeparator8)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordLinkedPanelLayout.createSequentialGroup()
                                                .addGroup(ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(ordLinkedPanelLayout.createSequentialGroup()
                                                                .addGroup(ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(ordLinkedPanelLayout.createSequentialGroup()
                                                                .addComponent(givenItem3)
                                                                .addGap(72, 72, 72)))
                                                .addGroup(ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(applyBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(eventBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                                        .addGroup(ordLinkedPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane8))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordLinkedPanelLayout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(375, 375, 375))
        );
        ordLinkedPanelLayout.setVerticalGroup(
                ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ordLinkedPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eventBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))
                                .addGap(27, 27, 27)
                                .addGroup(ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(applyBtn3)
                                        .addComponent(givenItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ordLinkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(labelTime3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Order Linked List", ordLinkedPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    ArrayList a;

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String switcher = (String) eventBox.getSelectedItem();

        long st = System.currentTimeMillis();
        switch (Objects.requireNonNull(switcher)) {

            case "build" -> {
                String[] s = teRead.getText().split(" ");
                a = new ArrayList(s.length * 4);
                for (String item : s) {
                    a.insert(Double.parseDouble(item));
                }
                teWrite.append(a.toString() + "\n");
            }
            case "delete" -> {
                a.delete(Double.parseDouble(givenItem.getText()));
                teWrite.append(a.toString() + "\n");

            }
            case "insert" -> {
                a.insert(Double.parseDouble(givenItem.getText()));
                teWrite.append(a.toString() + "\n");
            }
            case "selectionSort" -> {
                a.selectionSort();
                teWrite.append(a.toString() + "\n");
            }
            case "find" -> {
                int result = a.find(Double.parseDouble(givenItem.getText()));
                if (result == -1) {
                    teWrite.append("Not Found\n");
                } else {
                    teWrite.append("Found in: " + result + "\n");
                }
            }
            case "display" -> {
                teWrite.setText(a.toString() + "\n");
            }
        }
        long time = System.currentTimeMillis() - st;
        labelTime.setText(time + " millis");
    }

    private void eventBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String switcher = (String) eventBox.getSelectedItem();

        switch (Objects.requireNonNull(switcher)) {
            case "build", "selectionSort", "display" -> {
                givenItem.setEnabled(false);
            }
            default -> {
                givenItem.setEnabled(true);
            }
        }
    }

    private void eventBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String switcher = (String) eventBox1.getSelectedItem();

        switch (Objects.requireNonNull(switcher)) {
            case "build", "selectionSort", "display" -> {
                givenItem1.setEnabled(false);
            }
            default -> {
                givenItem1.setEnabled(true);
            }
        }
    }

    OrdArrayList ordA;

    private void applyBtn1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String switcher = (String) eventBox1.getSelectedItem();

        long st = System.currentTimeMillis();
        switch (Objects.requireNonNull(switcher)) {

            case "build" -> {
                String[] s = teRead1.getText().split(" ");
                ordA = new OrdArrayList(s.length * 4);
                for (String item : s) {
                    ordA.insert(Double.parseDouble(item));
                }
                teWrite1.append(ordA.toString() + "\n");
            }
            case "delete" -> {
                ordA.delete(Double.parseDouble(givenItem1.getText()));
                teWrite1.append(ordA.toString() + "\n");

            }
            case "insert" -> {
                ordA.insert(Double.parseDouble(givenItem1.getText()));
                teWrite1.append(ordA.toString() + "\n");
            }
            case "find" -> {
                int result = ordA.find(Double.parseDouble(givenItem1.getText()));
                if (result == -1) {
                    teWrite1.append("Not Found\n");
                } else {
                    teWrite1.append("Found in: " + result + "\n");
                }
            }
            case "display" -> {
                teWrite1.setText(ordA.toString() + "\n");
            }
        }
        long time = System.currentTimeMillis() - st;
        labelTime1.setText(time + " millis");

    }

    private void eventBox2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String switcher = (String) eventBox2.getSelectedItem();

        switch (Objects.requireNonNull(switcher)) {
            case "build", "selectionSort", "display" -> {
                givenItem2.setEnabled(false);
            }
            default -> {
                givenItem2.setEnabled(true);
            }
        }
    }

    LinkedList linkedList;

    private void applyBtn2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String switcher = (String) eventBox2.getSelectedItem();

        long st = System.currentTimeMillis();
        switch (Objects.requireNonNull(switcher)) {

            case "build" -> {
                String[] s = teRead2.getText().split(" ");
                linkedList = new LinkedList();
                for (String item : s) {
                    linkedList.insert(Double.parseDouble(item));
                }
                teWrite2.append(linkedList.toString() + "\n");
            }
            case "delete" -> {
                linkedList.delete(Double.parseDouble(givenItem2.getText()));
                teWrite2.append(linkedList.toString() + "\n");

            }
            case "insert" -> {
                linkedList.insert(Double.parseDouble(givenItem2.getText()));
                teWrite2.append(linkedList.toString() + "\n");
            }
            case "selectionSort" -> {
                linkedList.selectionSort();
                teWrite2.append(linkedList.toString() + "\n");
            }
            case "find" -> {
                int result = linkedList.find(Double.parseDouble(givenItem2.getText()));
                if (result == -1) {
                    teWrite2.append("Not Found\n");
                } else {
                    teWrite2.append("Found in: " + result + "\n");
                }
            }
            case "display" -> {
                teWrite2.setText(linkedList.toString() + "\n");
            }
        }
        long time = System.currentTimeMillis() - st;
        labelTime2.setText(time + " millis");
    }

    private void eventBox3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String switcher = (String) eventBox3.getSelectedItem();

        switch (Objects.requireNonNull(switcher)) {
            case "build", "selectionSort", "display" -> {
                givenItem3.setEnabled(false);
            }
            default -> {
                givenItem3.setEnabled(true);
            }
        }
    }

    OrdLinkedList ordLinkedList;

    private void applyBtn3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String switcher = (String) eventBox3.getSelectedItem();

        long st = System.currentTimeMillis();
        switch (Objects.requireNonNull(switcher)) {

            case "build" -> {
                String[] s = teRead3.getText().split(" ");
                ordLinkedList = new OrdLinkedList();
                for (String item : s) {
                    ordLinkedList.insert(Double.parseDouble(item));
                }
                teWrite3.append(ordLinkedList.toString() + "\n");
            }
            case "delete" -> {
                ordLinkedList.delete(Double.parseDouble(givenItem3.getText()));
                teWrite3.append(ordLinkedList.toString() + "\n");

            }
            case "insert" -> {
                ordLinkedList.insert(Double.parseDouble(givenItem3.getText()));
                teWrite3.append(ordLinkedList.toString() + "\n");
            }
            case "find" -> {
                int result = ordLinkedList.find(Double.parseDouble(givenItem3.getText()));
                if (result == -1) {
                    teWrite3.append("Not Found\n");
                } else {
                    teWrite3.append("Found in: " + result + "\n");
                }
            }
            case "display" -> {
                teWrite3.setText(ordLinkedList.toString() + "\n");
            }
        }
        long time = System.currentTimeMillis() - st;
        labelTime3.setText(time + " millis");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CS305GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CS305GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CS305GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CS305GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CS305GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton applyBtn;
    private javax.swing.JButton applyBtn1;
    private javax.swing.JButton applyBtn2;
    private javax.swing.JButton applyBtn3;
    private javax.swing.JPanel arrayPanel;
    private javax.swing.JComboBox<String> eventBox;
    private javax.swing.JComboBox<String> eventBox1;
    private javax.swing.JComboBox<String> eventBox2;
    private javax.swing.JComboBox<String> eventBox3;
    private javax.swing.JTextField givenItem;
    private javax.swing.JTextField givenItem1;
    private javax.swing.JTextField givenItem2;
    private javax.swing.JTextField givenItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelTime1;
    private javax.swing.JLabel labelTime2;
    private javax.swing.JLabel labelTime3;
    private javax.swing.JPanel linkedPanel;
    private javax.swing.JPanel ordArrayPanel;
    private javax.swing.JPanel ordLinkedPanel;
    private javax.swing.JTextArea teRead;
    private javax.swing.JTextArea teRead1;
    private javax.swing.JTextArea teRead2;
    private javax.swing.JTextArea teRead3;
    private javax.swing.JTextArea teWrite;
    private javax.swing.JTextArea teWrite1;
    private javax.swing.JTextArea teWrite2;
    private javax.swing.JTextArea teWrite3;
    // End of variables declaration
}